//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension API.Order {

    /**
    Cancel Order

    Cancels an open order. Must call /iserver/accounts endpoint prior to cancelling an order. Use /iservers/account/orders endpoint to review open-order(s) and get latest order status.
    */
    public enum DeleteIserverAccountByAccountIdOrderByOrderId {

        public static let service = APIService<Response>(id: "deleteIserverAccountByAccountIdOrderByOrderId", tag: "Order", method: "DELETE", path: "/iserver/account/{accountId}/order/{orderId}", hasBody: false, securityRequirements: [])

        public final class Request: APIRequest<Response> {

            public struct Options {

                /** account id, or fa group if deleting a group order */
                public var accountId: String

                /** Customer order id, use /iservers/account/orders endpoint to query orderId. */
                public var orderId: String

                public init(accountId: String, orderId: String) {
                    self.accountId = accountId
                    self.orderId = orderId
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: DeleteIserverAccountByAccountIdOrderByOrderId.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(accountId: String, orderId: String) {
                let options = Options(accountId: accountId, orderId: orderId)
                self.init(options: options)
            }

            public override var path: String {
                return super.path.replacingOccurrences(of: "{" + "accountId" + "}", with: "\(self.options.accountId)").replacingOccurrences(of: "{" + "orderId" + "}", with: "\(self.options.orderId)")
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {

            /** Cancels an open order. Must call /iserver/accounts endpoint prior to cancelling an order. Use /iservers/account/orders endpoint to review open-order(s) and get latest order status. */
            public class Status200: APIModel {

                public var account: String?

                public var conid: Int?

                public var msg: String?

                public var orderId: String?

                public init(account: String? = nil, conid: Int? = nil, msg: String? = nil, orderId: String? = nil) {
                    self.account = account
                    self.conid = conid
                    self.msg = msg
                    self.orderId = orderId
                }

                public required init(from decoder: Decoder) throws {
                    let container = try decoder.container(keyedBy: StringCodingKey.self)

                    account = try container.decodeIfPresent("account")
                    conid = try container.decodeIfPresent("conid")
                    msg = try container.decodeIfPresent("msg")
                    orderId = try container.decodeIfPresent("order_id")
                }

                public func encode(to encoder: Encoder) throws {
                    var container = encoder.container(keyedBy: StringCodingKey.self)

                    try container.encodeIfPresent(account, forKey: "account")
                    try container.encodeIfPresent(conid, forKey: "conid")
                    try container.encodeIfPresent(msg, forKey: "msg")
                    try container.encodeIfPresent(orderId, forKey: "order_id")
                }

                public func isEqual(to object: Any?) -> Bool {
                  guard let object = object as? Status200 else { return false }
                  guard self.account == object.account else { return false }
                  guard self.conid == object.conid else { return false }
                  guard self.msg == object.msg else { return false }
                  guard self.orderId == object.orderId else { return false }
                  return true
                }

                public static func == (lhs: Status200, rhs: Status200) -> Bool {
                    return lhs.isEqual(to: rhs)
                }
            }
            public typealias SuccessType = Status200

            /** returns an object with order id, message, conid and account id */
            case status200(Status200)

            public var success: Status200? {
                switch self {
                case .status200(let response): return response
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(Status200.self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
