//
// Body10.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Body10: Codable {

    public var conids: [Int]?

    public init(conids: [Int]?) {
        self.conids = conids
    }


}

