//
// IbcustentityinfoName.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct IbcustentityinfoName: Codable {

    public var salutation: String?
    public var firstName: String?
    public var lastName: String?

    public init(salutation: String?, firstName: String?, lastName: String?) {
        self.salutation = salutation
        self.firstName = firstName
        self.lastName = lastName
    }


}

