//
// InlineResponse20020.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse20020: Codable {

    public var orderId: String?
    public var localOrderId: String?
    public var orderStatus: String?

    public init(orderId: String?, localOrderId: String?, orderStatus: String?) {
        self.orderId = orderId
        self.localOrderId = localOrderId
        self.orderStatus = orderStatus
    }

    public enum CodingKeys: String, CodingKey { 
        case orderId = "order_id"
        case localOrderId = "local_order_id"
        case orderStatus = "order_status"
    }


}

