//
// InlineResponse200.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200: Codable {

    /** unread number */
    public var BN: Int?

    public init(BN: Int?) {
        self.BN = BN
    }


}

