//
// InlineResponse4001.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse4001: Codable {

    public var error: String?
    public var statusCode: Int?

    public init(error: String?, statusCode: Int?) {
        self.error = error
        self.statusCode = statusCode
    }


}

