//
// ModifyOrder.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ModifyOrder: Codable {

    public var acctId: String?
    public var conid: Int?
    /** for example LMT */
    public var orderType: String?
    public var outsideRTH: Bool?
    public var price: Double?
    public var auxPrice: Double?
    /** SELL or BUY */
    public var side: String?
    /** optional, not required */
    public var listingExchange: String?
    public var ticker: String?
    /** for example DAY */
    public var tif: String?
    /** usually integer, for some special cases can be float numbers */
    public var quantity: Double?

    public init(acctId: String?, conid: Int?, orderType: String?, outsideRTH: Bool?, price: Double?, auxPrice: Double?, side: String?, listingExchange: String?, ticker: String?, tif: String?, quantity: Double?) {
        self.acctId = acctId
        self.conid = conid
        self.orderType = orderType
        self.outsideRTH = outsideRTH
        self.price = price
        self.auxPrice = auxPrice
        self.side = side
        self.listingExchange = listingExchange
        self.ticker = ticker
        self.tif = tif
        self.quantity = quantity
    }


}

