//
// TransactionsTransactions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TransactionsTransactions: Codable {

    public var acctid: String?
    public var conid: Double?
    /** currency code */
    public var cur: String?
    /** Conversion rate from asset currency to response currency */
    public var fxRate: Double?
    /** Transaction description */
    public var desc: String?
    /** Date of transaction.  Epoch time, GMT */
    public var date: String?
    /** Transaction Type Name: Examples: \&quot;Sell\&quot;, \&quot;Buy\&quot;, \&quot;Corporate Action\&quot;, \&quot;Dividend Payment\&quot;, \&quot;Transfer\&quot;, \&quot;Payment in Lieu\&quot; Dividends and Transfers do not have price and quantity in response  */
    public var type: String?
    /** Not applicable for all transaction types */
    public var qty: Double?
    /** In asset currency. Not be applicable for all transaction types. */
    public var pr: Double?
    /** Raw value, no formatting. Net transaction amount (may include commission, tax). In asset currency */
    public var amt: Double?

    public init(acctid: String?, conid: Double?, cur: String?, fxRate: Double?, desc: String?, date: String?, type: String?, qty: Double?, pr: Double?, amt: Double?) {
        self.acctid = acctid
        self.conid = conid
        self.cur = cur
        self.fxRate = fxRate
        self.desc = desc
        self.date = date
        self.type = type
        self.qty = qty
        self.pr = pr
        self.amt = amt
    }


}

