//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension API.PortfolioAnalyst {

    /**
    Position's Transaction History

    transaction history for a given number of conids and accounts.
Types of transactions include dividend payments, buy and sell transactions, transfers.
    */
    public enum PostPaTransactions {

        public static let service = APIService<Response>(id: "postPaTransactions", tag: "PortfolioAnalyst", method: "POST", path: "/pa/transactions", hasBody: true, securityRequirements: [])

        public final class Request: APIRequest<Response> {

            /** transaction history for a given number of conids and accounts.
            Types of transactions include dividend payments, buy and sell transactions, transfers.
             */
            public class Body: APIModel {

                public var acctIds: [String]?

                public var conids: [Double]?

                /** optional defaults to USD. */
                public var currency: String?

                /** optional, default value is 90 */
                public var days: Double?

                public init(acctIds: [String]? = nil, conids: [Double]? = nil, currency: String? = nil, days: Double? = nil) {
                    self.acctIds = acctIds
                    self.conids = conids
                    self.currency = currency
                    self.days = days
                }

                public required init(from decoder: Decoder) throws {
                    let container = try decoder.container(keyedBy: StringCodingKey.self)

                    acctIds = try container.decodeArrayIfPresent("acctIds")
                    conids = try container.decodeArrayIfPresent("conids")
                    currency = try container.decodeIfPresent("currency")
                    days = try container.decodeIfPresent("days")
                }

                public func encode(to encoder: Encoder) throws {
                    var container = encoder.container(keyedBy: StringCodingKey.self)

                    try container.encodeIfPresent(acctIds, forKey: "acctIds")
                    try container.encodeIfPresent(conids, forKey: "conids")
                    try container.encodeIfPresent(currency, forKey: "currency")
                    try container.encodeIfPresent(days, forKey: "days")
                }

                public func isEqual(to object: Any?) -> Bool {
                  guard let object = object as? Body else { return false }
                  guard self.acctIds == object.acctIds else { return false }
                  guard self.conids == object.conids else { return false }
                  guard self.currency == object.currency else { return false }
                  guard self.days == object.days else { return false }
                  return true
                }

                public static func == (lhs: Body, rhs: Body) -> Bool {
                    return lhs.isEqual(to: rhs)
                }
            }

            public struct Options {

                public var acctIds: [String]?

                public var conids: [Double]?

                /** optional defaults to USD. */
                public var currency: String?

                /** optional, default value is 90 */
                public var days: Double?

                public init(acctIds: [String]? = nil, conids: [Double]? = nil, currency: String? = nil, days: Double? = nil) {
                    self.acctIds = acctIds
                    self.conids = conids
                    self.currency = currency
                    self.days = days
                }
            }

            public var options: Options

            public var body: Body

            public init(body: Body, options: Options, encoder: RequestEncoder? = nil) {
                self.body = body
                self.options = options
                super.init(service: PostPaTransactions.service) { defaultEncoder in
                    return try (encoder ?? defaultEncoder).encode(body)
                }
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(acctIds: [String]? = nil, conids: [Double]? = nil, currency: String? = nil, days: Double? = nil, body: Body) {
                let options = Options(acctIds: acctIds, conids: conids, currency: currency, days: days)
                self.init(body: body, options: options)
            }

            public override var formParameters: [String: Any] {
                var params: [String: Any] = [:]
                if let acctIds = options.acctIds {
                  params["acctIds"] = acctIds
                }
                if let conids = options.conids {
                  params["conids"] = conids
                }
                if let currency = options.currency {
                  params["currency"] = currency
                }
                if let days = options.days {
                  params["days"] = days
                }
                return params
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = Transactions

            /** returns an object */
            case status200(Transactions)

            public var success: Transactions? {
                switch self {
                case .status200(let response): return response
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(Transactions.self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
