//
// AlertResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AlertResponse: Codable {

    /** account id */
    public var account: String?
    public var orderId: Int?
    /** name of alert */
    public var alertName: String?
    /** The message you want to receive via email or text message */
    public var alertMessage: String?
    /** whether alert is active or not, so value can only be 0 or 1 */
    public var alertActive: Int?
    /** whether alert is repeatable or not, so value can only be 0 or 1 */
    public var alertRepeatable: Int?
    /** email address to receive alert */
    public var alertEmail: String?
    /** whether allowing to send email or not, so value can only be 0 or 1,  */
    public var alertSendMessage: Int?
    /** time in force, can only be GTC or GTD */
    public var tif: String?
    /** format, YYYYMMDD-HH:mm:ss  */
    public var expireTime: String?
    /** status of alert */
    public var orderStatus: String?
    /** value can only be 0 or 1, set to 1 if the alert can be triggered outside regular trading hours.  */
    public var outsideRth: Int?
    /** value can only be 0 or 1, set to 1 to enable the alert only in IBKR mobile  */
    public var itwsOrdersOnly: Int?
    /** value can only be 0 or 1, set to 1 to allow to show alert in pop-ups */
    public var alertShowPopup: Int?
    /** whether the alert has been triggered */
    public var alertTriggered: Bool?
    /** whether the alert can be edited */
    public var orderNotEditable: Bool?
    /** for MTA alert only, each user has a unique toolId and it will stay the same, do not send for normal alert  */
    public var toolId: Int?
    /** audio message to play when alert is triggered */
    public var alertPlayAudio: String?
    /** MTA alert only */
    public var alertMtaCurrency: String?
    /** MTA alert only */
    public var alertMtaDefaults: String?
    /** MTA alert only */
    public var timeZone: String?
    /** MTA alert only */
    public var alertDefaultType: String?
    /** size of conditions array */
    public var conditionSize: Int?
    /** whether allowing the condition can be triggered outside of regular trading hours, 1 means allow */
    public var conditionOutsideRth: Int?
    public var conditions: [AlertresponseConditions]?

    public init(account: String?, orderId: Int?, alertName: String?, alertMessage: String?, alertActive: Int?, alertRepeatable: Int?, alertEmail: String?, alertSendMessage: Int?, tif: String?, expireTime: String?, orderStatus: String?, outsideRth: Int?, itwsOrdersOnly: Int?, alertShowPopup: Int?, alertTriggered: Bool?, orderNotEditable: Bool?, toolId: Int?, alertPlayAudio: String?, alertMtaCurrency: String?, alertMtaDefaults: String?, timeZone: String?, alertDefaultType: String?, conditionSize: Int?, conditionOutsideRth: Int?, conditions: [AlertresponseConditions]?) {
        self.account = account
        self.orderId = orderId
        self.alertName = alertName
        self.alertMessage = alertMessage
        self.alertActive = alertActive
        self.alertRepeatable = alertRepeatable
        self.alertEmail = alertEmail
        self.alertSendMessage = alertSendMessage
        self.tif = tif
        self.expireTime = expireTime
        self.orderStatus = orderStatus
        self.outsideRth = outsideRth
        self.itwsOrdersOnly = itwsOrdersOnly
        self.alertShowPopup = alertShowPopup
        self.alertTriggered = alertTriggered
        self.orderNotEditable = orderNotEditable
        self.toolId = toolId
        self.alertPlayAudio = alertPlayAudio
        self.alertMtaCurrency = alertMtaCurrency
        self.alertMtaDefaults = alertMtaDefaults
        self.timeZone = timeZone
        self.alertDefaultType = alertDefaultType
        self.conditionSize = conditionSize
        self.conditionOutsideRth = conditionOutsideRth
        self.conditions = conditions
    }

    public enum CodingKeys: String, CodingKey { 
        case account
        case orderId = "order_id"
        case alertName = "alert_name"
        case alertMessage = "alert_message"
        case alertActive = "alert_active"
        case alertRepeatable = "alert_repeatable"
        case alertEmail = "alert_email"
        case alertSendMessage = "alert_send_message"
        case tif
        case expireTime = "expire_time"
        case orderStatus = "order_status"
        case outsideRth
        case itwsOrdersOnly = "itws_orders_only"
        case alertShowPopup = "alert_show_popup"
        case alertTriggered = "alert_triggered"
        case orderNotEditable = "order_not_editable"
        case toolId = "tool_id"
        case alertPlayAudio = "alert_play_audio"
        case alertMtaCurrency = "alert_mta_currency"
        case alertMtaDefaults = "alert_mta_defaults"
        case timeZone = "time_zone"
        case alertDefaultType = "alert_default_type"
        case conditionSize = "condition_size"
        case conditionOutsideRth = "condition_outside_rth"
        case conditions
    }


}

