//
// AlertrequestConditions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AlertrequestConditions: Codable {

    /** Types: 1-Price, 3-Time, 4-Margin, 5-Trade, 6-Volume, 7: MTA market 8: MTA Position, 9: MTA Acc. Daily PN&amp;  */
    public var type: Int?
    /** format, conid@exchange */
    public var conidex: String?
    /** optional, operator for the current condition, can be &gt;&#x3D; or &lt;&#x3D; */
    public var _operator: String?
    /** optional, only some type of conditions have triggerMethod */
    public var triggerMethod: String?
    /** can not be empty, can pass default value \&quot;*\&quot; */
    public var value: String?
    /** \&quot;a\&quot; means \&quot;AND\&quot;, \&quot;o\&quot; means \&quot;OR\&quot;, \&quot;n\&quot; means \&quot;END\&quot;, the last one condition in the condition array should \&quot;n\&quot;  */
    public var logicBind: String?
    /** only needed for some MTA alert condition */
    public var timeZone: String?

    public init(type: Int?, conidex: String?, _operator: String?, triggerMethod: String?, value: String?, logicBind: String?, timeZone: String?) {
        self.type = type
        self.conidex = conidex
        self._operator = _operator
        self.triggerMethod = triggerMethod
        self.value = value
        self.logicBind = logicBind
        self.timeZone = timeZone
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case conidex
        case _operator = "operator"
        case triggerMethod
        case value
        case logicBind
        case timeZone
    }


}

