//
// Body4.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Body4: Codable {

    public var acctIds: [String]?
    public var conids: [Double]?
    /** optional defaults to USD. */
    public var currency: String?
    /** optional, default value is 90 */
    public var days: Double?

    public init(acctIds: [String]?, conids: [Double]?, currency: String?, days: Double?) {
        self.acctIds = acctIds
        self.conids = conids
        self.currency = currency
        self.days = days
    }


}

