//
// Body6.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Body6: Codable {

    /** alert id(order id) */
    public var alertId: Int?
    /** 1 to activate, 0 to deactivate */
    public var alertActive: Int?

    public init(alertId: Int?, alertActive: Int?) {
        self.alertId = alertId
        self.alertActive = alertActive
    }


}

