//
// CalendarRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CalendarRequest: Codable {

    public var date: CalendarRequestDate?
    public var filters: CalendarRequestFilters?

    public init(date: CalendarRequestDate?, filters: CalendarRequestFilters?) {
        self.date = date
        self.filters = filters
    }


}

