//
// IbcustentityinfoEntities.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct IbcustentityinfoEntities: Codable {

    public var canTrade: Bool?
    public var canSign: Bool?
    public var type: String?
    public var name: IbcustentityinfoName?
    public var address: IbcustentityinfoAddress?
    public var identDocs: [JSONValue]?

    public init(canTrade: Bool?, canSign: Bool?, type: String?, name: IbcustentityinfoName?, address: IbcustentityinfoAddress?, identDocs: [JSONValue]?) {
        self.canTrade = canTrade
        self.canSign = canSign
        self.type = type
        self.name = name
        self.address = address
        self.identDocs = identDocs
    }


}

