//
// InlineResponse20010.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse20010: Codable {

    public var ACCTID: Position?

    public init(ACCTID: Position?) {
        self.ACCTID = ACCTID
    }


}

