//
// InlineResponse20027ScanTypeList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse20027ScanTypeList: Codable {

    public var displayName: String?
    public var code: String?
    public var instruments: [String]?

    public init(displayName: String?, code: String?, instruments: [String]?) {
        self.displayName = displayName
        self.code = code
        self.instruments = instruments
    }

    public enum CodingKeys: String, CodingKey { 
        case displayName = "display_name"
        case code
        case instruments
    }


}

