//
// InlineResponse2003.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2003: Codable {

    public var T: Int?
    public var V: Int?

    public init(T: Int?, V: Int?) {
        self.T = T
        self.V = V
    }


}

