//
// InlineResponse20014.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse20014: Codable {

    public var orderId: Int?
    /** account id */
    public var account: String?
    public var alertName: String?
    /** Value can only be 0 or 1, 1 means active */
    public var alertActive: Int?
    /** format, YYYYMMDD-HH:mm:ss, the time when you created the alert  */
    public var orderTime: String?
    /** whether the alert has been triggered or not */
    public var alertTriggered: Bool?
    /** whether the alert can be repeatable or not, value can be 1 or 0. 1 means true */
    public var alertRepeatable: Int?

    public init(orderId: Int?, account: String?, alertName: String?, alertActive: Int?, orderTime: String?, alertTriggered: Bool?, alertRepeatable: Int?) {
        self.orderId = orderId
        self.account = account
        self.alertName = alertName
        self.alertActive = alertActive
        self.orderTime = orderTime
        self.alertTriggered = alertTriggered
        self.alertRepeatable = alertRepeatable
    }

    public enum CodingKeys: String, CodingKey { 
        case orderId = "order_id"
        case account
        case alertName = "alert_name"
        case alertActive = "alert_active"
        case orderTime = "order_time"
        case alertTriggered = "alert_triggered"
        case alertRepeatable = "alert_repeatable"
    }


}

