//
// InlineResponse2002.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2002: Codable {

    /** disclaimer message */
    public var DT: String?
    /** fyi code */
    public var FC: String?

    public init(DT: String?, FC: String?) {
        self.DT = DT
        self.FC = FC
    }


}

