//
// InlineResponse2007.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2007: Codable {

    /** 1 for Live, 2 for Paper */
    public var LOGIN_TYPE: Double?
    /** Username */
    public var USER_NAME: String?
    /** User ID */
    public var USER_ID: Double?
    /** Time in milliseconds until session expires. Caller needs to call the again to re-validate session */
    public var expire: Double?
    /** true if session was validated; false if not. */
    public var RESULT: Bool?
    /** Time of session validation */
    public var AUTH_TIME: Double?

    public init(LOGIN_TYPE: Double?, USER_NAME: String?, USER_ID: Double?, expire: Double?, RESULT: Bool?, AUTH_TIME: Double?) {
        self.LOGIN_TYPE = LOGIN_TYPE
        self.USER_NAME = USER_NAME
        self.USER_ID = USER_ID
        self.expire = expire
        self.RESULT = RESULT
        self.AUTH_TIME = AUTH_TIME
    }


}

