//
// InlineResponse20022.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse20022: Codable {

    /** Last Price */
    public var _31: String?
    /** Symbol */
    public var _55: String?
    /** Text */
    public var _58: String?
    /** High */
    public var _70: String?
    /** Low */
    public var _71: String?
    /** Position */
    public var _72: String?
    /** Market Value */
    public var _73: String?
    /** Average Price */
    public var _74: String?
    /** Unrealized PnL */
    public var _75: String?
    /** Formatted position */
    public var _76: String?
    /** Formatted Unrealized PnL */
    public var _77: String?
    /** Daily PnL */
    public var _78: String?
    /** Change Price */
    public var _82: String?
    /** Change Percent */
    public var _83: String?
    /** Bid Price */
    public var _84: String?
    /** Ask Size */
    public var _85: String?
    /** Ask Price */
    public var _86: String?
    /** Volume */
    public var _87: String?
    /** Bid Size */
    public var _88: String?
    /** Exchange */
    public var _6004: String?
    /** Conid */
    public var _6008: String?
    /** Security Type */
    public var _6070: String?
    /** Months */
    public var _6072: String?
    /** Regular Expiry */
    public var _6073: String?
    /** Marker for market data delivery method (similar to request id) */
    public var _6119: String?
    /** Underlying Conid. Use /trsrv/secdef to get more information about the security */
    public var _6457: String?
    /** Market Data Availability. The field may contain two chars. The first char is the primary code: R &#x3D; Realtime, D &#x3D; Delayed, Z &#x3D; Frozen, Y &#x3D; Frozen Delayed. The second char is the secondary code: P &#x3D; Snapshot Available, p &#x3D; Consolidated.  */
    public var _6509: String?
    /** Company name */
    public var _7051: String?
    /** Last Size */
    public var _7059: String?
    /** Conid + Exchange */
    public var _7094: String?
    /** Contract Description */
    public var _7219: String?
    /** Contract Description */
    public var _7220: String?
    /** Listing Exchange */
    public var _7221: String?
    /** Industry */
    public var _7280: String?
    /** Category */
    public var _7281: String?
    /** Average Daily Volume */
    public var _7282: String?
    /** Historic Volume (30d) */
    public var _7284: String?
    /** Put/Call Ratio */
    public var _7285: String?
    /** Dividend Amount */
    public var _7286: String?
    /** Dividend Yield % */
    public var _7287: String?
    /** Ex-date of the dividend */
    public var _7288: String?
    /** Market Cap */
    public var _7289: String?
    /** P/E */
    public var _7290: String?
    /** EPS */
    public var _7291: String?
    /** Cost Basis */
    public var _7292: String?
    /** 52 Week High */
    public var _7293: String?
    /** 52 Week Low */
    public var _7294: String?
    /** Open Price */
    public var _7295: String?
    /** Close Price */
    public var _7296: String?
    /** Delta */
    public var _7308: String?
    /** Gamma */
    public var _7309: String?
    /** Theta */
    public var _7310: String?
    /** Vega */
    public var _7311: String?
    /** Implied volatility of the option */
    public var _7633: String?
    public var serverId: String?
    public var conid: Int?
    public var updated: Int?

    public init(_31: String?, _55: String?, _58: String?, _70: String?, _71: String?, _72: String?, _73: String?, _74: String?, _75: String?, _76: String?, _77: String?, _78: String?, _82: String?, _83: String?, _84: String?, _85: String?, _86: String?, _87: String?, _88: String?, _6004: String?, _6008: String?, _6070: String?, _6072: String?, _6073: String?, _6119: String?, _6457: String?, _6509: String?, _7051: String?, _7059: String?, _7094: String?, _7219: String?, _7220: String?, _7221: String?, _7280: String?, _7281: String?, _7282: String?, _7284: String?, _7285: String?, _7286: String?, _7287: String?, _7288: String?, _7289: String?, _7290: String?, _7291: String?, _7292: String?, _7293: String?, _7294: String?, _7295: String?, _7296: String?, _7308: String?, _7309: String?, _7310: String?, _7311: String?, _7633: String?, serverId: String?, conid: Int?, updated: Int?) {
        self._31 = _31
        self._55 = _55
        self._58 = _58
        self._70 = _70
        self._71 = _71
        self._72 = _72
        self._73 = _73
        self._74 = _74
        self._75 = _75
        self._76 = _76
        self._77 = _77
        self._78 = _78
        self._82 = _82
        self._83 = _83
        self._84 = _84
        self._85 = _85
        self._86 = _86
        self._87 = _87
        self._88 = _88
        self._6004 = _6004
        self._6008 = _6008
        self._6070 = _6070
        self._6072 = _6072
        self._6073 = _6073
        self._6119 = _6119
        self._6457 = _6457
        self._6509 = _6509
        self._7051 = _7051
        self._7059 = _7059
        self._7094 = _7094
        self._7219 = _7219
        self._7220 = _7220
        self._7221 = _7221
        self._7280 = _7280
        self._7281 = _7281
        self._7282 = _7282
        self._7284 = _7284
        self._7285 = _7285
        self._7286 = _7286
        self._7287 = _7287
        self._7288 = _7288
        self._7289 = _7289
        self._7290 = _7290
        self._7291 = _7291
        self._7292 = _7292
        self._7293 = _7293
        self._7294 = _7294
        self._7295 = _7295
        self._7296 = _7296
        self._7308 = _7308
        self._7309 = _7309
        self._7310 = _7310
        self._7311 = _7311
        self._7633 = _7633
        self.serverId = serverId
        self.conid = conid
        self.updated = updated
    }

    public enum CodingKeys: String, CodingKey { 
        case _31 = "31"
        case _55 = "55"
        case _58 = "58"
        case _70 = "70"
        case _71 = "71"
        case _72 = "72"
        case _73 = "73"
        case _74 = "74"
        case _75 = "75"
        case _76 = "76"
        case _77 = "77"
        case _78 = "78"
        case _82 = "82"
        case _83 = "83"
        case _84 = "84"
        case _85 = "85"
        case _86 = "86"
        case _87 = "87"
        case _88 = "88"
        case _6004 = "6004"
        case _6008 = "6008"
        case _6070 = "6070"
        case _6072 = "6072"
        case _6073 = "6073"
        case _6119 = "6119"
        case _6457 = "6457"
        case _6509 = "6509"
        case _7051 = "7051"
        case _7059 = "7059"
        case _7094 = "7094"
        case _7219 = "7219"
        case _7220 = "7220"
        case _7221 = "7221"
        case _7280 = "7280"
        case _7281 = "7281"
        case _7282 = "7282"
        case _7284 = "7284"
        case _7285 = "7285"
        case _7286 = "7286"
        case _7287 = "7287"
        case _7288 = "7288"
        case _7289 = "7289"
        case _7290 = "7290"
        case _7291 = "7291"
        case _7292 = "7292"
        case _7293 = "7293"
        case _7294 = "7294"
        case _7295 = "7295"
        case _7296 = "7296"
        case _7308 = "7308"
        case _7309 = "7309"
        case _7310 = "7310"
        case _7311 = "7311"
        case _7633 = "7633"
        case serverId = "server_id"
        case conid
        case updated = "_updated"
    }


}

