//
// InlineResponse20031.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse20031: Codable {

    public var symbol: Futures?

    public init(symbol: Futures?) {
        self.symbol = symbol
    }


}

