//
// InlineResponse20027InstrumentList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse20027InstrumentList: Codable {

    public var displayName: String?
    public var type: String?
    public var filters: [String]?

    public init(displayName: String?, type: String?, filters: [String]?) {
        self.displayName = displayName
        self.type = type
        self.filters = filters
    }

    public enum CodingKeys: String, CodingKey { 
        case displayName = "display_name"
        case type
        case filters
    }


}

