//
// SetAccount.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SetAccount: Codable {

    /** Account ID */
    public var acctId: String?

    public init(acctId: String?) {
        self.acctId = acctId
    }


}

