//
// Stocks.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** This is an array of object(s), there could be multiple results under same symbol  */
public typealias Stocks = [StocksInner]
