//
// Symbol.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Symbol: Codable {

    /** symbol or name to be searched */
    public var symbol: String
    /** should be true if the search is to be performed by name. false by default. */
    public var name: Bool?
    /** If search is done by name, only the assets provided in this field will be returned. Currently, only STK is supported. */
    public var secType: String?

    public init(symbol: String, name: Bool?, secType: String?) {
        self.symbol = symbol
        self.name = name
        self.secType = secType
    }


}

