//
// SystemError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SystemError: Codable {

    public var error: String?

    public init(error: String?) {
        self.error = error
    }


}

