//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** future contract information */
public class Future: APIModel {

    /** conid of the future contract */
    public var conid: Int?

    public var expirationDate: String?

    /** last trading day */
    public var ltd: String?

    public var symbol: String?

    public var underlyingConid: Int?

    public init(conid: Int? = nil, expirationDate: String? = nil, ltd: String? = nil, symbol: String? = nil, underlyingConid: Int? = nil) {
        self.conid = conid
        self.expirationDate = expirationDate
        self.ltd = ltd
        self.symbol = symbol
        self.underlyingConid = underlyingConid
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        conid = try container.decodeIfPresent("conid")
        expirationDate = try container.decodeIfPresent("expirationDate")
        ltd = try container.decodeIfPresent("ltd")
        symbol = try container.decodeIfPresent("symbol")
        underlyingConid = try container.decodeIfPresent("underlyingConid")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(conid, forKey: "conid")
        try container.encodeIfPresent(expirationDate, forKey: "expirationDate")
        try container.encodeIfPresent(ltd, forKey: "ltd")
        try container.encodeIfPresent(symbol, forKey: "symbol")
        try container.encodeIfPresent(underlyingConid, forKey: "underlyingConid")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? Future else { return false }
      guard self.conid == object.conid else { return false }
      guard self.expirationDate == object.expirationDate else { return false }
      guard self.ltd == object.ltd else { return false }
      guard self.symbol == object.symbol else { return false }
      guard self.underlyingConid == object.underlyingConid else { return false }
      return true
    }

    public static func == (lhs: Future, rhs: Future) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
