//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct IBInd: APIModel {

    public let conid: Double?

    public init(conid: Double? = nil) {
        self.conid = conid
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        conid = try container.decodeIfPresent("conid")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(conid, forKey: "conid")
    }

}
