//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class SetAccount: APIModel {

    /** Account ID */
    public var acctId: String?

    public init(acctId: String? = nil) {
        self.acctId = acctId
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        acctId = try container.decodeIfPresent("acctId")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(acctId, forKey: "acctId")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? SetAccount else { return false }
      guard self.acctId == object.acctId else { return false }
      return true
    }

    public static func == (lhs: SetAccount, rhs: SetAccount) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
