//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** future contract information */
public class Stock: APIModel {

    public var assetClass: String?

    /** company name in Chinese */
    public var chineseName: String?

    /** array of contracts from different exchanges */
    public var contracts: [Contracts]?

    /** company name */
    public var name: String?

    /** future contract information */
    public class Contracts: APIModel {

        /** conid of the stock contract */
        public var conid: Int?

        public var exchange: String?

        public init(conid: Int? = nil, exchange: String? = nil) {
            self.conid = conid
            self.exchange = exchange
        }

        public required init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: StringCodingKey.self)

            conid = try container.decodeIfPresent("conid")
            exchange = try container.decodeIfPresent("exchange")
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: StringCodingKey.self)

            try container.encodeIfPresent(conid, forKey: "conid")
            try container.encodeIfPresent(exchange, forKey: "exchange")
        }

        public func isEqual(to object: Any?) -> Bool {
          guard let object = object as? Contracts else { return false }
          guard self.conid == object.conid else { return false }
          guard self.exchange == object.exchange else { return false }
          return true
        }

        public static func == (lhs: Contracts, rhs: Contracts) -> Bool {
            return lhs.isEqual(to: rhs)
        }
    }

    public init(assetClass: String? = nil, chineseName: String? = nil, contracts: [Contracts]? = nil, name: String? = nil) {
        self.assetClass = assetClass
        self.chineseName = chineseName
        self.contracts = contracts
        self.name = name
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        assetClass = try container.decodeIfPresent("assetClass")
        chineseName = try container.decodeIfPresent("chineseName")
        contracts = try container.decodeArrayIfPresent("contracts")
        name = try container.decodeIfPresent("name")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(assetClass, forKey: "assetClass")
        try container.encodeIfPresent(chineseName, forKey: "chineseName")
        try container.encodeIfPresent(contracts, forKey: "contracts")
        try container.encodeIfPresent(name, forKey: "name")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? Stock else { return false }
      guard self.assetClass == object.assetClass else { return false }
      guard self.chineseName == object.chineseName else { return false }
      guard self.contracts == object.contracts else { return false }
      guard self.name == object.name else { return false }
      return true
    }

    public static func == (lhs: Stock, rhs: Stock) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
